- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_RIVER_0C909BE1E }}
    action: "upload"
    app_location: "/" 
    api_location: "" 
    output_location: ""
    skip_app_build: true  # Add this line
    github_id_token: ${{ steps.idtoken.outputs.result }}
